version: "3.9"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./Config/sonarr/data:/config
      - /tvseries:/tv 
      - /downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 7878:7878
    volumes:
      - ./Config/radarr/data:/config
      - /movies:/movies
      - /downloads:/downloads
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./Config/jellyfin/data:/config
      - /tvseries:/data/tvshows
      - /movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./Config/sabnzbd/data:/config
      - /downloads:/downloads
      - /incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
